### ISSUE TITLE
add entity_id constrained autosuggest back end support

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#9] opened 2016-07-15 00:54 UTC
#_1 add ability to auto determine common region/variable groups
_2 take each region/variable group and add into columns
_3 shard the columns into multiple datasets

examples:

Some helpful soql querie:

https://dev.socrata.com/foundry/odn.data.socrata.com/hytw-gi3p

https://odn.data.socrata.com/resource/sutp-685r.json?$group=variable&$select=variable,count(variable)

https://odn.data.socrata.com/resource/sutp-685r.json?$group=variable&$select=variable,count(variable)&$where=starts_with(variable,%20%27jobs%27)

Note: stuff w/ the same count is LIKELY to have the same entities.

**Comment by aaasen** [comment] 2016-09-10 07:24
Duplicate of #54. Closing.

**Closed by aaasen** 2016-09-10 07:24 UTC
